PORTNAME=	ldapd
DISTVERSION=	7.3.20230810
CATEGORIES=	www
MASTER_SITES=	OPENBSD/LibreSSL:libressl
DISTFILES=	libressl-${SSL}.tar.gz:libressl

MAINTAINER=	koue@chaosophia.net
COMMENT=	OpenBSD ldap server
WWW=		https://github.com/koue/ldapd

LICENSE=	BSD3CLAUSE

USES=		uidfix

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	ldapd \
		libevent:libevent \
		libimsg:libimsg
GH_TAGNAME=	${LIBIMSG}:libimsg \
		${LIBEVENT}:libevent

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

# XXX Static libraries with PIE are currently unsupported.
MAKE_ARGS+=	WITHOUT_PIE=true

CFLAGS+=	-Wall \
		-I${WRKDIR}/libressl-${SSL}/include \
		-I${WRKSRC_libimsg}/src/lib/libutil \
		-I${WRKSRC_libevent}/src/lib/libevent

LDFLAGS+=	-L${WRKSRC_libimsg}/src/lib/libutil \
		-L${WRKSRC_libevent}/src/lib/libevent

USERS=		www
GROUPS=		www

SSL= 		3.8.0
LIBEVENT=	7.3.20230714
LIBIMSG= 	7.3.20230714

post-patch:
	${REINPLACE_CMD} -e 's|libimsg/src||g' \
			 -e 's|libevent||g' ${WRKSRC}/Makefile
	${REINPLACE_CMD} -e 's|/etc/ldapd.conf|${PREFIX}/etc/ldapd.conf|g' \
		${WRKSRC}/src/usr.sbin/ldapd/ldapd.h

pre-configure:
	@(cd ${WRKDIR} && ${EXTRACT_CMD} ${EXTRACT_BEFORE_ARGS} ${DISTDIR}/libressl-${SSL}.tar.gz ${EXTRACT_AFTER_ARGS})
	@(cd ${WRKDIR}/libressl-${SSL} && ${SETENV} ./configure && ${SETENV} ${MAKE_ENV} ${MAKE})
	@(cd ${WRKSRC_libimsg} && ${SETENV} ${MAKE_ENV} ${MAKE})
	@(cd ${WRKSRC_libevent} && ${SETENV} ${MAKE_ENV} ${MAKE})

post-configure:
	${REINPLACE_CMD} 's|-ltls|${WRKDIR}/libressl-${SSL}/tls/.libs/libtls.a|g' \
		${WRKSRC}/src/usr.bin/ldap/Makefile
	${REINPLACE_CMD} 's|-lssl|${WRKDIR}/libressl-${SSL}/ssl/.libs/libssl.a|g' \
		${WRKSRC}/src/usr.bin/ldap/Makefile
	${REINPLACE_CMD} 's|-lcrypto|${WRKDIR}/libressl-${SSL}/crypto/.libs/libcrypto.a|g' \
		${WRKSRC}/src/usr.bin/ldap/Makefile
	${REINPLACE_CMD} 's|-ltls|${WRKDIR}/libressl-${SSL}/tls/.libs/libtls.a|g' \
		${WRKSRC}/src/usr.sbin/ldapd/Makefile
	${REINPLACE_CMD} 's|-lssl|${WRKDIR}/libressl-${SSL}/ssl/.libs/libssl.a|g' \
		${WRKSRC}/src/usr.sbin/ldapd/Makefile
	${REINPLACE_CMD} 's|-lcrypto|${WRKDIR}/libressl-${SSL}/crypto/.libs/libcrypto.a|g' \
		${WRKSRC}/src/usr.sbin/ldapd/Makefile
	${REINPLACE_CMD} 's|-ltls|${WRKDIR}/libressl-${SSL}/tls/.libs/libtls.a|g' \
		${WRKSRC}/src/usr.sbin/ldapctl/Makefile
	${REINPLACE_CMD} 's|-lssl|${WRKDIR}/libressl-${SSL}/ssl/.libs/libssl.a|g' \
		${WRKSRC}/src/usr.sbin/ldapctl/Makefile
	${REINPLACE_CMD} 's|-lcrypto|${WRKDIR}/libressl-${SSL}/crypto/.libs/libcrypto.a|g' \
		${WRKSRC}/src/usr.sbin/ldapctl/Makefile

post-install:
	${INSTALL_DATA} ${WRKSRC}/src/etc/examples/ldapd.conf \
		${STAGEDIR}${PREFIX}/etc/ldapd.conf.sample

.include <bsd.port.mk>
